// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aa: typeof import('./components/aa.vue')['default']
    CurrentDate: typeof import('./components/CurrentDate.vue')['default']
    CustomSelect: typeof import('./components/CustomSelect.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Tensorflowjs: typeof import('./components/Tensorflowjs.vue')['default']
    Three: typeof import('./components/Three.vue')['default']
    Threejs: typeof import('./components/Threejs.vue')['default']
  }
}
